steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy','--entry-point','GarbageCollect', '--runtime','go113','--trigger-http','--allow-unauthenticated','--memory', '128']
  env: ['GOPATH=/gopath']
  dir: './src/fn_garbage_collect'